- NewFiles/JuanBecerra.java
- roster.md
Added the NewFiles directory for other interns to add files to
> Appended to roster and added NewFiles directory

- cameronSenorNewFile
- roster.md
Please let me know if I messed up anything, am new to GitHub.
> Cameron Senor roster append + file

- roster.md
Added myself to roster and up to date to original repository
> Added Luis to roster

- roster.md
> Roster Update

- roster.md
Intro to me is added to roster.md.
> shay added

- NewFiles/SophiaSangervasiNewFile.js
- roster.md
Hello!
My name is Sophia Sangervasi and here are my changes to the roster.md and my new file.
> Added SophiaSangervasiNewFile and added bio

- CommentingPractice/comment-practice.js
- CommentingPractice/services/spaces.js
fixed the export statement and used Amontes code
> Second try for the pull request

- CommentingPractice/comment-practice.js
Fixed the expression that evaluates to Undefined
> Kobayashi branch

- CommentingPractice/comment-practice.js
- CommentingPractice/services/product.js
- test.c
Was testing git command lines with creating and deleting files from branches
> Testing git command lines with creating and deleting files from branches

- CommentingPractice/comment-practice.js
- CommentingPractice/services/arithmetic.js
Also added some debug code to the comment practice file
> Added arithmetic module

- CommentingPractice/comment-practice.js
- CommentingPractice/model/rome.js
> added my own module to represent the glory of rome

- CommentingPractice/comment-practice.js
- CommentingPractice/services/vowelSwitcher.js
> Added vowel switching method

- CommentingPractice/comment-practice.js
- CommentingPractice/model/teammate.js
- CommentingPractice/test/backwardsTests.js
-Was able to compile using npm run-script debug 
-Used somebody else file from model in comment-practice
-Made a file in model titled teammate 
-Created a unit test for my backwardsName file. (Still learning how to use mocha) But was able to pass 2 tests.
> Completed all three tasks

- CommentingPractice/comment-practice.js
- CommentingPractice/services/colorConverter.js
- CommentingPractice/test/colorConverter.test.js
added colorConverter.js in services
added colorConverrter.test.js in tests
added "import colorConverter" in comment-practice.js
> Add support for converting hex to rgb and rgb to hex within colorConverter service

- CommentingPractice/model/teammate.js
fix misspelling from tname to tName
> Fixed teammate.js

- CommentingPractice/comment-practice.js
- CommentingPractice/model/plant.js
- CommentingPractice/model/teammate.js
- CommentingPractice/test/spacesTest.js
Created plant.js, test spaces.js, used teammate.js
> finished task 3

- CommentingPractice/test/allModels.js
Bringing in new models to be covered by the test coverage check.
> Bringing in new models to be covered by the test coverage check.

- CommentingPractice/services/arithmetic.js
- CommentingPractice/test/moduloTest.js
added modulo function and created file with unit tests
> added modulo function to arithmetic.js

- CommentingPractice/comment-practice.js
- CommentingPractice/model/Shape.js
- CommentingPractice/services/sumOfNumber.js
- CommentingPractice/test/sumOfNumberTest.js
- Added Shape.js, a basic shape library
- Added test code to comment-practice.js
- Extended input range of sumOfNumber function in sumOfNumber.js
- Added a new test to sumTest.js to test new feature
> Added a shapes lib, added to comment practice, extended sumOfNumber input range

- .github/workflows/node.js.yml
- CommentingPractice/package.json
Attempt to run on all branches.
Removing node 10 runs.
Adding a run of the compile script
> Adjusting git action workflow
